package com.github.flombois.models;

/**
 * Represents error details from an API response, following RFC 7807 Problem Details format.
 * <p>
 * This class is used to model error responses from the Nager.Date API, containing
 * structured information about what went wrong with a request.
 * </p>
 *
 * @since 1.0
 */
public class ProblemDetails {

    private String detail;
    private String instance;
    private int status;
    private String title;
    private String type;

    /**
     * Returns a human-readable explanation specific to this occurrence of the problem.
     *
     * @return the detail message
     */
    public String getDetail() {
        return detail;
    }

    /**
     * Sets the detail message.
     *
     * @param detail the detail message
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * Returns a URI reference that identifies the specific occurrence of the problem.
     *
     * @return the instance URI
     */
    public String getInstance() {
        return instance;
    }

    /**
     * Sets the instance URI.
     *
     * @param instance the instance URI
     */
    public void setInstance(String instance) {
        this.instance = instance;
    }

    /**
     * Returns the HTTP status code generated by the origin server for this occurrence.
     *
     * @return the HTTP status code
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the HTTP status code.
     *
     * @param status the HTTP status code
     */
    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * Returns a short, human-readable summary of the problem type.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the title.
     *
     * @param title the title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns a URI reference that identifies the problem type.
     *
     * @return the type URI
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the type URI.
     *
     * @param type the type URI
     */
    public void setType(String type) {
        this.type = type;
    }
}
